CREATE DATABASE SMS;
USE SMS;

CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE  INT
);

-- ADD COLUMN USING ALTER COMMAND
ALTER TABLE STUDENT
ADD EMAIL VARCHAR(100);

SELECT * FROM STUDENT;

-- MODIFY COLUMNS
ALTER TABLE STUDENT
MODIFY NAME VARCHAR(100);

-- DROP COLUMN
ALTER TABLE STUDENT
DROP COLUMN AGE;

SELECT * FROM STUDENT;

DROP TABLE STUDENT;

-- AGAIN CRATE TABLE TO PERFORM TRUNCATE COMMMAND
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE  INT
);

INSERT INTO STUDENT VALUES(101,"Aditi",23);

select * from student;

-- delete all data but structure remain
TRUNCATE TABLE STUDENT;

SELECT * FROM STUDENT;

-- RENAME COLUMN
RENAME TABLE STUDENT 
TO STUDENT_10TH_CLASS;



